# evolution_chains.py — Maps species to their evolved forms for PvP ranking projection
# Only includes evolutions that are PvP-relevant (i.e., fit under GL/UL caps)
# IVs are PRESERVED through evolution in Pokémon GO
import re
EVOLUTION_CHAINS = {
    # Kanto
    "Bulbasaur":    ["Ivysaur", "Venusaur"],
    "Ivysaur":      ["Venusaur"],
    "Charmander":   ["Charmeleon", "Charizard"],
    "Charmeleon":   ["Charizard"],
    "Squirtle":     ["Wartortle", "Blastoise"],
    "Wartortle":    ["Blastoise"],
    "Caterpie":     ["Metapod", "Butterfree"],
    "Metapod":      ["Butterfree"],
    "Weedle":       ["Kakuna", "Beedrill"],
    "Kakuna":       ["Beedrill"],
    "Pidgey":       ["Pidgeotto", "Pidgeot"],
    "Pidgeotto":    ["Pidgeot"],
    "Rattata":      ["Raticate"],
    "Spearow":      ["Fearow"],
    "Ekans":        ["Arbok"],
    "Pikachu":      ["Raichu"],
    "Sandshrew":    ["Sandslash"],
    "Nidoran♀":     ["Nidorina", "Nidoqueen"],
    "Nidorina":     ["Nidoqueen"],
    "Nidoran♂":     ["Nidorino", "Nidoking"],
    "Nidorino":     ["Nidoking"],
    "Clefairy":     ["Clefable"],
    "Vulpix":       ["Ninetales"],
    "Jigglypuff":   ["Wigglytuff"],
    "Zubat":        ["Golbat", "Crobat"],
    "Golbat":       ["Crobat"],
    "Oddish":       ["Gloom", "Vileplume"],
    "Gloom":        ["Vileplume", "Bellossom"],
    "Paras":        ["Parasect"],
    "Venonat":      ["Venomoth"],
    "Diglett":      ["Dugtrio"],
    "Meowth":       ["Persian"],
    "Psyduck":      ["Golduck"],
    "Mankey":       ["Primeape"],
    "Growlithe":    ["Arcanine"],
    "Poliwag":      ["Poliwhirl", "Poliwrath"],
    "Poliwhirl":    ["Poliwrath", "Politoed"],
    "Abra":         ["Kadabra", "Alakazam"],
    "Kadabra":      ["Alakazam"],
    "Machop":       ["Machoke", "Machamp"],
    "Machoke":      ["Machamp"],
    "Bellsprout":   ["Weepinbell", "Victreebel"],
    "Weepinbell":   ["Victreebel"],
    "Tentacool":    ["Tentacruel"],
    "Geodude":      ["Graveler", "Golem"],
    "Graveler":     ["Golem"],
    "Ponyta":       ["Rapidash"],
    "Slowpoke":     ["Slowbro", "Slowking"],
    "Magnemite":    ["Magneton", "Magnezone"],
    "Magneton":     ["Magnezone"],
    "Doduo":        ["Dodrio"],
    "Seel":         ["Dewgong"],
    "Grimer":       ["Muk"],
    "Shellder":     ["Cloyster"],
    "Gastly":       ["Haunter", "Gengar"],
    "Haunter":      ["Gengar"],
    "Drowzee":      ["Hypno"],
    "Krabby":       ["Kingler"],
    "Voltorb":      ["Electrode"],
    # Intentionally omitted and defined in regional section "Exeggcute":    ["Exeggutor"],
    "Cubone":       ["Marowak"],
    "Horsea":       ["Seadra", "Kingdra"],
    "Seadra":       ["Kingdra"],
    "Goldeen":      ["Seaking"],
    "Staryu":       ["Starmie"],
    "Scyther":      ["Scizor"],
    "Magmar":       ["Magmortar"],
    "Electabuzz":   ["Electivire"],
    "Eevee":        ["Vaporeon","Jolteon","Flareon","Espeon","Umbreon","Leafeon","Glaceon","Sylveon"],
    "Dratini":      ["Dragonair", "Dragonite"],
    "Dragonair":    ["Dragonite"],
    # Johto
    "Chikorita":    ["Bayleef", "Meganium"],
    "Bayleef":      ["Meganium"],
    "Cyndaquil":    ["Quilava", "Typhlosion"],
    "Quilava":      ["Typhlosion"],
    "Totodile":     ["Croconaw", "Feraligatr"],
    "Croconaw":     ["Feraligatr"],
    "Sentret":      ["Furret"],
    "Hoothoot":     ["Noctowl"],
    "Ledyba":       ["Ledian"],
    "Spinarak":     ["Ariados"],
    "Chinchou":     ["Lanturn"],
    "Togepi":       ["Togetic", "Togekiss"],
    "Togetic":      ["Togekiss"],
    "Mareep":       ["Flaaffy", "Ampharos"],
    "Flaaffy":      ["Ampharos"],
    "Marill":       ["Azumarill"],
    "Sudowoodo":    [],
    "Hoppip":       ["Skiploom", "Jumpluff"],
    "Skiploom":     ["Jumpluff"],
    "Wooper":       ["Quagsire"],
    "Murkrow":      ["Honchkrow"],
    "Misdreavus":   ["Mismagius"],
    "Sneasel":      ["Weavile"],
    "Slugma":       ["Magcargo"],
    "Swinub":       ["Piloswine", "Mamoswine"],
    "Piloswine":    ["Mamoswine"],
    "Corsola":      [],
    "Remoraid":     ["Octillery"],
    "Houndour":     ["Houndoom"],
    "Phanpy":       ["Donphan"],
    "Larvitar":     ["Pupitar", "Tyranitar"],
    "Pupitar":      ["Tyranitar"],
    # Hoenn
    "Treecko":      ["Grovyle", "Sceptile"],
    "Grovyle":      ["Sceptile"],
    "Torchic":      ["Combusken", "Blaziken"],
    "Combusken":    ["Blaziken"],
    "Mudkip":       ["Marshtomp", "Swampert"],
    "Marshtomp":    ["Swampert"],
    "Ralts":        ["Kirlia", "Gardevoir", "Gallade"],
    "Kirlia":       ["Gardevoir", "Gallade"],
    "Shroomish":    ["Breloom"],
    "Slakoth":      ["Vigoroth", "Slaking"],
    "Vigoroth":     ["Slaking"],
    "Makuhita":     ["Hariyama"],
    "Aron":         ["Lairon", "Aggron"],
    "Lairon":       ["Aggron"],
    "Meditite":     ["Medicham"],
    "Electrike":    ["Manectric"],
    "Gulpin":       ["Swalot"],
    "Carvanha":     ["Sharpedo"],
    "Numel":        ["Camerupt"],
    "Trapinch":     ["Vibrava", "Flygon"],
    "Vibrava":      ["Flygon"],
    "Cacnea":       ["Cacturne"],
    "Swablu":       ["Altaria"],
    "Zangoose":     [],
    "Seviper":      [],
    "Barboach":     ["Whiscash"],
    "Shuppet":      ["Banette"],
    "Duskull":      ["Dusclops", "Dusknoir"],
    "Dusclops":     ["Dusknoir"],
    "Snorunt":      ["Glalie", "Froslass"],
    "Spheal":       ["Sealeo", "Walrein"],
    "Sealeo":       ["Walrein"],
    "Bagon":        ["Shelgon", "Salamence"],
    "Shelgon":      ["Salamence"],
    "Beldum":       ["Metang", "Metagross"],
    "Metang":       ["Metagross"],
    # Sinnoh
    "Turtwig":      ["Grotle", "Torterra"],
    "Grotle":       ["Torterra"],
    "Chimchar":     ["Monferno", "Infernape"],
    "Monferno":     ["Infernape"],
    "Piplup":       ["Prinplup", "Empoleon"],
    "Prinplup":     ["Empoleon"],
    "Starly":       ["Staravia", "Staraptor"],
    "Staravia":     ["Staraptor"],
    "Bidoof":       ["Bibarel"],
    "Kricketot":    ["Kricketune"],
    "Shinx":        ["Luxio", "Luxray"],
    "Luxio":        ["Luxray"],
    "Budew":        ["Roselia", "Roserade"],
    "Roselia":      ["Roserade"],
    "Cranidos":     ["Rampardos"],
    "Shieldon":     ["Bastiodon"],
    "Burmy":        ["Wormadam", "Mothim"],
    "Combee":       ["Vespiquen"],
    "Buizel":       ["Floatzel"],
    "Cherubi":      ["Cherrim"],
    "Shellos":      ["Gastrodon"],
    "Drifloon":     ["Drifblim"],
    "Buneary":      ["Lopunny"],
    "Glameow":      ["Purugly"],
    "Stunky":       ["Skuntank"],
    "Gible":        ["Gabite", "Garchomp"],
    "Gabite":       ["Garchomp"],
    "Hippopotas":   ["Hippowdon"],
    "Skorupi":      ["Drapion"],
    "Croagunk":     ["Toxicroak"],
    "Finneon":      ["Lumineon"],
    "Snover":       ["Abomasnow"],
    "Riolu":        ["Lucario"],
    # Unova
    "Snivy":        ["Servine", "Serperior"],
    "Servine":      ["Serperior"],
    "Tepig":        ["Pignite", "Emboar"],
    "Pignite":      ["Emboar"],
    "Oshawott":     ["Dewott", "Samurott"],
    "Dewott":       ["Samurott"],
    "Patrat":       ["Watchog"],
    "Lillipup":     ["Herdier", "Stoutland"],
    "Herdier":      ["Stoutland"],
    "Purrloin":     ["Liepard"],
    "Pidove":       ["Tranquill", "Unfezant"],
    "Tranquill":    ["Unfezant"],
    "Blitzle":      ["Zebstrika"],
    "Roggenrola":   ["Boldore", "Gigalith"],
    "Boldore":      ["Gigalith"],
    "Woobat":       ["Swoobat"],
    "Drilbur":      ["Excadrill"],
    "Timburr":      ["Gurdurr", "Conkeldurr"],
    "Gurdurr":      ["Conkeldurr"],
    "Tympole":      ["Palpitoad", "Seismitoad"],
    "Palpitoad":    ["Seismitoad"],
    "Sewaddle":     ["Swadloon", "Leavanny"],
    "Swadloon":     ["Leavanny"],
    "Venipede":     ["Whirlipede", "Scolipede"],
    "Whirlipede":   ["Scolipede"],
    "Sandile":      ["Krokorok", "Krookodile"],
    "Krokorok":     ["Krookodile"],
    "Darumaka":     ["Darmanitan"],
    "Dwebble":      ["Crustle"],
    "Scraggy":      ["Scrafty"],
    "Yamask":       ["Cofagrigus"],
    "Tirtouga":     ["Carracosta"],
    "Archen":       ["Archeops"],
    "Trubbish":     ["Garbodor"],
    "Zorua":        ["Zoroark"],
    "Minccino":     ["Cinccino"],
    "Gothita":      ["Gothorita", "Gothitelle"],
    "Gothorita":    ["Gothitelle"],
    "Solosis":      ["Duosion", "Reuniclus"],
    "Duosion":      ["Reuniclus"],
    "Ducklett":     ["Swanna"],
    "Vanillite":    ["Vanillish", "Vanilluxe"],
    "Vanillish":    ["Vanilluxe"],
    "Karrablast":   ["Escavalier"],
    "Foongus":      ["Amoonguss"],
    "Frillish":     ["Jellicent"],
    "Joltik":       ["Galvantula"],
    "Ferroseed":    ["Ferrothorn"],
    "Klink":        ["Klang", "Klinklang"],
    "Klang":        ["Klinklang"],
    "Elgyem":       ["Beheeyem"],
    "Litwick":      ["Lampent", "Chandelure"],
    "Lampent":      ["Chandelure"],
    "Axew":         ["Fraxure", "Haxorus"],
    "Fraxure":      ["Haxorus"],
    "Cubchoo":      ["Beartic"],
    "Cryogonal":    [],
    "Shelmet":      ["Accelgor"],
    "Stunfisk":     [],
    "Mienfoo":      ["Mienshao"],
    "Druddigon":    [],
    "Golett":       ["Golurk"],
    "Pawniard":     ["Bisharp"],
    "Bouffalant":   [],
    "Rufflet":      ["Braviary"],
    "Vullaby":      ["Mandibuzz"],
    "Deino":        ["Zweilous", "Hydreigon"],
    "Zweilous":     ["Hydreigon"],
    "Larvesta":     ["Volcarona"],
    # Kalos
    "Chespin":      ["Quilladin", "Chesnaught"],
    "Quilladin":    ["Chesnaught"],
    "Fennekin":     ["Braixen", "Delphox"],
    "Braixen":      ["Delphox"],
    "Froakie":      ["Frogadier", "Greninja"],
    "Frogadier":    ["Greninja"],
    "Bunnelby":     ["Diggersby"],
    "Fletchling":   ["Fletchinder", "Talonflame"],
    "Fletchinder":  ["Talonflame"],
    "Scatterbug":   ["Spewpa", "Vivillon"],
    "Spewpa":       ["Vivillon"],
    "Litleo":       ["Pyroar"],
    "Flabébé":      ["Floette", "Florges"],
    "Floette":      ["Florges"],
    "Skiddo":       ["Gogoat"],
    "Pancham":      ["Pangoro"],
    "Espurr":       ["Meowstic"],
    "Honedge":      ["Doublade", "Aegislash"],
    "Doublade":     ["Aegislash"],
    "Spritzee":     ["Aromatisse"],
    "Swirlix":      ["Slurpuff"],
    "Inkay":        ["Malamar"],
    "Binacle":      ["Barbaracle"],
    "Skrelp":       ["Dragalge"],
    "Clauncher":    ["Clawitzer"],
    "Helioptile":   ["Heliolisk"],
    "Tyrunt":       ["Tyrantrum"],
    "Amaura":       ["Aurorus"],
    "Sylveon":      [],
    "Goomy":        ["Sliggoo", "Goodra"],
    "Sliggoo":      ["Goodra"],
    "Klefki":       [],
    "Phantump":     ["Trevenant"],
    "Pumpkaboo Small":   ["Gourgeist Small"],
    "Pumpkaboo Average": ["Gourgeist Average"],
    "Pumpkaboo Large":   ["Gourgeist Large"],
    "Pumpkaboo Super":   ["Gourgeist Super"],
    "Gourgeist Small":   [],
    "Gourgeist Average": [],
    "Gourgeist Large":   [],
    "Gourgeist Super":   [],
    "Bergmite":     ["Avalugg"],
    "Noibat":       ["Noivern"],
    # Alola
    "Rowlet":       ["Dartrix", "Decidueye"],
    "Dartrix":      ["Decidueye"],
    "Litten":       ["Torracat", "Incineroar"],
    "Torracat":     ["Incineroar"],
    "Popplio":      ["Brionne", "Primarina"],
    "Brionne":      ["Primarina"],
    "Pikipek":      ["Trumbeak", "Toucannon"],
    "Trumbeak":     ["Toucannon"],
    "Yungoos":      ["Gumshoos"],
    "Grubbin":      ["Charjabug", "Vikavolt"],
    "Charjabug":    ["Vikavolt"],
    "Crabrawler":   ["Crabominable"],
    "Cutiefly":     ["Ribombee"],
    "Rockruff":     ["Lycanroc"],
    "Wishiwashi":   [],
    "Dewpider":     ["Araquanid"],
    "Fomantis":     ["Lurantis"],
    "Morelull":     ["Shiinotic"],
    "Salandit":     ["Salazzle"],
    "Stufful":      ["Bewear"],
    "Bounsweet":    ["Steenee", "Tsareena"],
    "Steenee":      ["Tsareena"],
    "Wimpod":       ["Golisopod"],
    "Sandygast":    ["Palossand"],
    "Jangmo-o":     ["Hakamo-o", "Kommo-o"],
    "Hakamo-o":     ["Kommo-o"],
    "Cosmog":       ["Cosmoem", "Solgaleo"],  # or Lunala
    "Cosmoem":      ["Solgaleo"],
    # Galar
    "Grookey":      ["Thwackey", "Rillaboom"],
    "Thwackey":     ["Rillaboom"],
    "Scorbunny":    ["Raboot", "Cinderace"],
    "Raboot":       ["Cinderace"],
    "Sobble":       ["Drizzile", "Inteleon"],
    "Drizzile":     ["Inteleon"],
    "Skwovet":      ["Greedent"],
    "Rookidee":     ["Corvisquire", "Corviknight"],
    "Corvisquire":  ["Corviknight"],
    "Blipbug":      ["Dottler", "Orbeetle"],
    "Dottler":      ["Orbeetle"],
    "Nickit":       ["Thievul"],
    "Gossifleur":   ["Eldegoss"],
    "Wooloo":       ["Dubwool"],
    "Chewtle":      ["Drednaw"],
    "Yamper":       ["Boltund"],
    "Rolycoly":     ["Carkol", "Coalossal"],
    "Carkol":       ["Coalossal"],
    "Silicobra":    ["Sandaconda"],
    "Cramorant":    [],
    "Arrokuda":     ["Barraskewda"],
    "Toxel":        ["Toxtricity"],
    "Sizzlipede":   ["Centiskorch"],
    "Clobbopus":    ["Grapploct"],
    "Sinistea":     ["Polteageist"],
    "Hatenna":      ["Hattrem", "Hatterene"],
    "Hattrem":      ["Hatterene"],
    "Impidimp":     ["Morgrem", "Grimmsnarl"],
    "Morgrem":      ["Grimmsnarl"],
    "Milcery":      ["Alcremie"],
    "Falinks":      [],
    "Snom":         ["Frosmoth"],
    "Stonjourner":  [],
    "Eiscue":       [],
    "Indeedee":     [],
    "Morpeko":      [],
    "Dreepy":       ["Drakloak", "Dragapult"],
    "Drakloak":     ["Dragapult"],
    # Paldea
    "Sprigatito":   ["Floragato", "Meowscarada"],
    "Floragato":    ["Meowscarada"],
    "Fuecoco":      ["Crocalor", "Skeledirge"],
    "Crocalor":     ["Skeledirge"],
    "Quaxly":       ["Quaxwell", "Quaquaval"],
    "Quaxwell":     ["Quaquaval"],
    "Lechonk":      ["Oinkologne"],
    "Tarountula":   ["Spidops"],
    "Nymble":       ["Lokix"],
    "Pawmi":        ["Pawmo", "Pawmot"],
    "Pawmo":        ["Pawmot"],
    "Tandemaus":    ["Maushold"],
    "Fidough":      ["Dachsbun"],
    "Smoliv":       ["Dolliv", "Arboliva"],
    "Dolliv":       ["Arboliva"],
    "Nacli":        ["Naclstack", "Garganacl"],
    "Naclstack":    ["Garganacl"],
    "Tadbulb":      ["Bellibolt"],
    "Wattrel":      ["Kilowattrel"],
    "Maschiff":     ["Mabosstiff"],
    "Shroodle":     ["Grafaiai"],
    "Bramblin":     ["Brambleghast"],
    "Toedscool":    ["Toedscruel"],
    "Klawf":        [],
    "Capsakid":     ["Scovillain"],
    "Rellor":       ["Rabsca"],
    "Flittle":      ["Espathra"],
    "Tinkatink":    ["Tinkatuff", "Tinkaton"],
    "Tinkatuff":    ["Tinkaton"],
    "Wiglett":      ["Wugtrio"],
    "Finizen":      ["Palafin"],
    "Varoom":       ["Revavroom"],
    "Cyclizar":     [],
    "Orthworm":     [],
    "Glimmet":      ["Glimmora"],
    "Greavard":     ["Houndstone"],
    "Flamigo":      [],
    "Cetoddle":     ["Cetitan"],
    "Veluza":       [],
    "Dondozo":      [],
    "Tatsugiri":    [],
    "Frigibax":     ["Arctibax", "Baxcalibur"],
    "Arctibax":     ["Baxcalibur"],
    # Monkey trio (the Panpour case!)
    "Panpour":      ["Simipour"],
    "Pansage":      ["Simisage"],
    "Pansear":      ["Simisear"],
    # ── Regional Variants ────────────────────────────────────────────

    # Alolan
    "Rattata (Alolan)": ["Raticate (Alolan)"],
    "Sandshrew (Alolan)": ["Sandslash (Alolan)"],
    "Vulpix (Alolan)": ["Ninetales (Alolan)"],
    "Diglett (Alolan)": ["Dugtrio (Alolan)"],
    "Meowth (Alolan)": ["Persian (Alolan)"],
    "Geodude (Alolan)": ["Graveler (Alolan)", "Golem (Alolan)"],
    "Graveler (Alolan)": ["Golem (Alolan)"],
    "Grimer (Alolan)": ["Muk (Alolan)"],
    "Exeggcute": ["Exeggutor", "Exeggutor (Alolan)"],  # same base, two evos
    "Raichu (Alolan)": [],  # final form, no further evo
    "Marowak (Alolan)": [],
    "Persian (Alolan)": [],
    "Ninetales (Alolan)": [],
    "Sandslash (Alolan)": [],
    "Dugtrio (Alolan)": [],
    "Golem (Alolan)": [],
    "Muk (Alolan)": [],
    "Exeggutor (Alolan)": [],
    "Raticate (Alolan)": [],

    # Galarian
    "Meowth (Galarian)": ["Perrserker"],
    "Ponyta (Galarian)": ["Rapidash (Galarian)"],
    "Slowpoke (Galarian)": ["Slowbro (Galarian)", "Slowking (Galarian)"],
    "Farfetch'd (Galarian)": ["Sirfetch'd"],
    "Weezing (Galarian)": [],
    "Mr. Mime (Galarian)": ["Mr. Rime"],
    "Corsola (Galarian)": ["Cursola"],
    "Zigzagoon (Galarian)": ["Linoone (Galarian)", "Obstagoon"],
    "Linoone (Galarian)": ["Obstagoon"],
    "Darumaka (Galarian)": ["Darmanitan (Galarian)"],
    "Yamask (Galarian)": ["Runerigus"],
    "Stunfisk (Galarian)": [],
    "Perrserker": [],
    "Rapidash (Galarian)": [],
    "Slowbro (Galarian)": [],
    "Slowking (Galarian)": [],
    "Sirfetch'd": [],
    "Mr. Rime": [],
    "Cursola": [],
    "Obstagoon": [],
    "Runerigus": [],
    "Darmanitan (Galarian)": [],

    # Hisuian
    "Growlithe (Hisuian)": ["Arcanine (Hisuian)"],
    "Voltorb (Hisuian)": ["Electrode (Hisuian)"],
    "Typhlosion (Hisuian)": [],
    "Samurott (Hisuian)": [],
    "Lilligant (Hisuian)": [],
    "Zorua (Hisuian)": ["Zoroark (Hisuian)"],
    "Braviary (Hisuian)": [],
    "Sliggoo (Hisuian)": ["Goodra (Hisuian)"],
    "Goodra (Hisuian)": [],
    "Avalugg (Hisuian)": [],
    "Decidueye (Hisuian)": [],
    "Sneasel (Hisuian)": ["Sneasler"],
    "Qwilfish (Hisuian)": ["Overqwil"],
    "Arcanine (Hisuian)": [],
    "Electrode (Hisuian)": [],
    "Zoroark (Hisuian)": [],
    "Sneasler": [],
    "Overqwil": [],
    "Basculegion": [],

    # Paldean
    "Wooper (Paldean)": ["Clodsire"],
    "Tauros (Paldean)": [],  # combat/blaze/aqua breeds — no evo
    "Clodsire": [],
}
# ---------------------------------------------------------------------------
# Mega Energy family resolution
# ---------------------------------------------------------------------------
# Pokémon GO stores and displays Mega Energy per evolutionary line, not per
# species — a Charmander's screen shows "Charizard Mega Energy X/Y" even
# though Charmander itself cannot Mega Evolve. This means the resource-block
# layout (single Mega Energy vs. X/Y split vs. none at all) is a property of
# the family's Mega-capable member, not of whichever stage was actually
# scanned. This is a small, finite, occasionally-updated list — extend it
# whenever Niantic adds a new Mega species.
MEGA_CAPABLE_SPECIES = {
    "Venusaur", "Charizard", "Blastoise", "Beedrill", "Pidgeot",
    "Alakazam", "Slowbro", "Gengar", "Kangaskhan", "Pinsir",
    "Gyarados", "Aerodactyl", "Mewtwo", "Ampharos", "Steelix",
    "Scizor", "Heracross", "Houndoom", "Tyranitar", "Blaziken",
    "Gardevoir", "Mawile", "Aggron", "Medicham", "Manectric",
    "Banette", "Absol", "Garchomp", "Lucario", "Abomasnow",
    "Gallade", "Audino", "Diancie", "Sableye", "Sharpedo",
    "Camerupt", "Altaria", "Glalie", "Salamence", "Metagross",
    "Latias", "Latios", "Rayquaza", "Lopunny", "Swampert",
    "Skarmory",
    # ... extend as Niantic adds more Mega species
}


def get_mega_energy_family(species: str) -> str | None:
    """
    Returns the species name whose Mega Energy is tracked/displayed for this
    Pokémon's evolutionary line — even on a pre-evolution's screen, since GO
    shows the family's Mega Energy on every stage, not just the final form.
    Returns None if no member of this line can Mega Evolve.
    """
    name = normalize_name(species)
    if name in MEGA_CAPABLE_SPECIES:
        return name
    for evo in get_evolutions(name):
        if evo in MEGA_CAPABLE_SPECIES:
            return evo
        deeper = get_mega_energy_family(evo)
        if deeper:
            return deeper
    return None

def normalize_name(name: str) -> str:
    result = name.strip().title()
    # Fix apostrophe mangling: "Farfetch'D" → "Farfetch'd"
    return re.sub(r"'([A-Z])", lambda m: "'" + m.group(1).lower(), result)

def get_evolutions(species: str) -> list[str]:
    """Return the list of evolved forms for a species. Empty list if none/unknown."""
    return EVOLUTION_CHAINS.get(normalize_name(species), [])

def _build_family_root_map() -> dict[str, str]:
    """
    Maps every species to the root (first-stage) member of its evolutionary
    line — the species whose name appears in the in-game Candy label (e.g.
    Charizard's candy pool is displayed as "Charmander Candy").
    """
    all_evolutions = set()
    for evos in EVOLUTION_CHAINS.values():
        all_evolutions.update(evos)

    roots = [s for s in EVOLUTION_CHAINS if s not in all_evolutions]

    family_root = {}
    for root in roots:
        family_root[root] = root
        stack = list(EVOLUTION_CHAINS.get(root, []))
        while stack:
            evo = stack.pop()
            family_root[evo] = root
            stack.extend(EVOLUTION_CHAINS.get(evo, []))
    return family_root


_FAMILY_ROOT_MAP = _build_family_root_map()


def get_candy_family(species: str) -> str:
    """
    Returns the family-root species name that this Pokémon's Candy pool is
    tracked and labeled under in-game — shared across the whole
    evolutionary line, not just the currently-scanned stage.
    """
    name = normalize_name(species)
    return _FAMILY_ROOT_MAP.get(name, name)